#include "dianji.h"


void go(int i)
{
	IN_SET(A1_PORT,A1_PIN,SET);
	IN_SET(A2_PORT,A2_PIN,RESET);
	PWM_SET(A_HANDLE,A_CHANNLE,i);
	
	IN_SET(B1_PORT,B1_PIN,SET);
	IN_SET(B2_PORT,B2_PIN,RESET);
	PWM_SET(B_HANDLE,B_CHANNLE,i);
	
	IN_SET(C1_PORT,C1_PIN,RESET);
	IN_SET(C2_PORT,C2_PIN,SET);
	PWM_SET(C_HANDLE,C_CHANNLE,i);
	
	IN_SET(D1_PORT,D1_PIN,SET);
	IN_SET(D2_PORT,D2_PIN,RESET);
	PWM_SET(D_HANDLE,D_CHANNLE,i);
	
}

void back(int x)
{
	IN_SET(A1_PORT,A1_PIN,RESET);
	IN_SET(A2_PORT,A2_PIN,SET);
	PWM_SET(A_HANDLE,A_CHANNLE,x);

	IN_SET(B1_PORT,B1_PIN,RESET);
	IN_SET(B2_PORT,B2_PIN,SET);
	PWM_SET(B_HANDLE,B_CHANNLE,x);
	
	IN_SET(C1_PORT,C1_PIN,SET);
	IN_SET(C2_PORT,C2_PIN,RESET);
	PWM_SET(C_HANDLE,C_CHANNLE,x);
	
	IN_SET(D1_PORT,D1_PIN,RESET);
	IN_SET(D2_PORT,D2_PIN,SET);
	PWM_SET(D_HANDLE,D_CHANNLE,x);
}

void Stop(void)
{
	IN_SET(A1_PORT,A1_PIN,RESET);
	IN_SET(A2_PORT,A2_PIN,RESET);
	
	IN_SET(B1_PORT,B1_PIN,RESET);
	IN_SET(B2_PORT,B2_PIN,RESET);
	
	IN_SET(C1_PORT,C1_PIN,RESET);
	IN_SET(C2_PORT,C2_PIN,RESET);
	
	IN_SET(D1_PORT,D1_PIN,RESET);
	IN_SET(D2_PORT,D2_PIN,RESET);
}	
void Left_set(int i,int e,int speed)
{
	if(i>0)
	{
	IN_SET(A1_PORT,A1_PIN,SET);
	IN_SET(A2_PORT,A2_PIN,RESET);
	IN_SET(C1_PORT,C1_PIN,RESET);
	IN_SET(C2_PORT,C2_PIN,SET);
	PWM_SET(C_HANDLE,C_CHANNLE,i);
	PWM_SET(A_HANDLE,A_CHANNLE,speed);	
	}
	else
	{
	IN_SET(A1_PORT,A1_PIN,RESET);
	IN_SET(A2_PORT,A2_PIN,SET);
	IN_SET(C1_PORT,C1_PIN,SET);
	IN_SET(C2_PORT,C2_PIN,RESET);
	PWM_SET(C_HANDLE,C_CHANNLE,-i);
	PWM_SET(A_HANDLE,A_CHANNLE,speed);
	}
	if(e==3) 
	{PWM_SET(C_HANDLE,C_CHANNLE,-i);}
	if(e==-3) 	
	{
	IN_SET(A1_PORT,A1_PIN,SET);
	IN_SET(A2_PORT,A2_PIN,RESET);
	IN_SET(C1_PORT,C1_PIN,RESET);
	IN_SET(C2_PORT,C2_PIN,SET);
	PWM_SET(C_HANDLE,C_CHANNLE,i);}

}

void Right_set(int i,int e,int speed)
{
	if(i>0)
	{
	IN_SET(B1_PORT,B1_PIN,SET);
	IN_SET(B2_PORT,B2_PIN,RESET);
	IN_SET(D1_PORT,D1_PIN,SET);
	IN_SET(D2_PORT,D2_PIN,RESET);
	PWM_SET(D_HANDLE,D_CHANNLE,i);
	PWM_SET(B_HANDLE,B_CHANNLE,speed);
	}
	else
	{
	IN_SET(B1_PORT,B1_PIN,RESET);
	IN_SET(B2_PORT,B2_PIN,SET);
	IN_SET(D1_PORT,D1_PIN,RESET);
	IN_SET(D2_PORT,D2_PIN,SET);
	PWM_SET(D_HANDLE,D_CHANNLE,-i);
	PWM_SET(B_HANDLE,B_CHANNLE,speed);
	}
	if(e==3) 
	{
	IN_SET(B1_PORT,B1_PIN,RESET);
	IN_SET(B2_PORT,B2_PIN,SET);
	IN_SET(D1_PORT,D1_PIN,RESET);
	IN_SET(D2_PORT,D2_PIN,SET);
	PWM_SET(D_HANDLE,D_CHANNLE,i);}
	if(e==-3) 
	{PWM_SET(D_HANDLE,D_CHANNLE,-i);}
}




